package com.ixigua.completion.fonts;

public class IOSFonts {
    public final static String[] IOS_9_FONT_LIST = new String[] {
            "PingFang HK",
            "PingFang SC",
            "PingFang TC",
            "Kohinoor Bangla",
            "Hiragino Sans",
    };
//    iOS 9 以上支持的字体，
    public final static String[] IOS_8_FONT_LIST = new String[]{
            "Academy Engraved LET",
            "Al Nile",
            "American Typewriter",
            "Apple Color Emoji",
            "Apple SD Gothic Neo",
            "Arial",
            "Arial Hebrew",
            "Arial Rounded MT Bold",
            "Avenir",
            "Avenir Next",
            "Avenir Next Condensed",
            "Bangla Sangam MN",
            "Baskerville",
            "Bodoni Ornaments",
            "Bradley Hand",
            "Chalkboard SE",
            "Chalkduster",
            "Cochin",
            "Copperplate",
            "Courier",
            "Courier New",
            "DB LCD Temp",
            "DIN Alternate",
            "DIN Condensed",
            "Damascus",
            "Devanagari Sangam MN",
            "Didot",
            "Diwan Mishafi",
            "Euphemia UCAS",
            "Farah",
            "Futura",
            "Geeza Pro",
            "Georgia",
            "Gill Sans",
            "Gujarati Sangam MN",
            "Gurmukhi MN",
            "Heiti SC",
            "Heiti TC",
            "Helvetica",
            "Helvetica Neue",
            "Hiragino Kaku Gothic ProN",
            "Hiragino Mincho ProN",
            "Hoefler Text",
            "Iowan Old Style",
            "Kailasa",
            "Kannada Sangam MN",
            "KhmerSangamMN",
            "KohinoorDevanagari",
            "Kohinor Telugu",
            "LaoSangamMN",
            "Malayalam Sangam MN",
            "Marion",
            "Marker Felt",
            "Menlo",
            "Noteworthy",
            "Optima",
            "Oriya Sangam MN",
            "Palatino",
            "Papyrus",
            "Party LET",
            "San Francisco",
            "Savoye Let",
            "Sinhala Sangam MN",
            "Snell Roundhand",
            "Superclarendon",
            "Symbol",
            "Tamil Sangam MN",
            "Telugu Sangam MN",
            "Thonburi",
            "Times New Roman",
            "Trebuchet MS",
            "Verdana",
            "Zapf Dingbats",
            "Zapfino",
    };
}
